class DatosGuatemala {
  // Lista de departamentos
  static const List<String> departamentos = [
    'Alta Verapaz',
    'Baja Verapaz',
    'Chimaltenango',
    'Chiquimula',
    'El Progreso',
    'El Petén',
    'Escuintla',
    'Guatemala',
    'Huehuetenango',
    'Izabal',
    'Jalapa',
    'Jutiapa',
    'Quetzaltenango',
    'Quiché',
    'Retalhuleu',
    'Sacatepéquez',
    'San Marcos',
    'Santa Rosa',
    'Sololá',
    'Suchitepéquez',
    'Totonicapán',
    'Zacapa',
  ];

  // Mapa de departamentos con sus municipios
  static const Map<String, List<String>> municipiosPorDepartamento = {
    'Guatemala': [
      'Guatemala (Ciudad de Guatemala)',
      'Santa Catarina Pinula',
      'San José Pinula',
      'San José del Golfo',
      'Palencia',
      'Chinautla',
      'San Pedro Ayampuc',
      'Mixco',
      'San Pedro Sacatepéquez',
      'San Juan Sacatepéquez',
      'San Raymundo',
      'Chuarrancho',
      'Fraijanes',
      'Amatitlán',
      'Villa Nueva',
      'Villa Canales',
      'San Miguel Petapa',
    ],
    'Alta Verapaz': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE ALTA VERAPAZ
      'Cobán',
      'Santa Cruz Verapaz',
      'San Cristóbal Verapaz',
      'Tactic',
      'Tamahú',
      'Tucurú',
      'Panzós',
      'Senahú',
      'San Pedro Carchá',
      'San Juan Chamelco',
      'Lanquín',
      'Cahabón',
      'Chisec',
      'Chahal',
      'Fray Bartolomé de las Casas',
      'Santa María Cahabón',
      'Raxruhá',
    ],
    'Baja Verapaz': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE BAJA VERAPAZ
      'Salamá',
      'San Miguel Chicaj',
      'Rabinal',
      'Cubulco',
      'Granados',
      'El Chol',
      'San Jerónimo',
      'Purulhá',
    ],
    'Chimaltenango': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE CHIMALTENANGO
      'Chimaltenango',
      'San José Poaquil',
      'San Martín Jilotepeque',
      'Comalapa (San Juan Comalapa)',
      'Santa Apolonia',
      'Tecpán Guatemala',
      'Patzún',
      'Pochuta',
      'Patzicía',
      'Santa Cruz Balanyá',
      'Acatenango',
      'Yepocapa',
      'Parramos',
      'Zaragoza',
      'El Tejar',
      'San Andrés Itzapa',
    ],
    'Chiquimula': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE CHIQUIMULA
      'Chiquimula',
      'San José La Arada',
      'San Juan Ermita',
      'Jocotán',
      'Camotán',
      'Olopa',
      'Esquipulas',
      'Concepción Las Minas',
      'Quezaltepeque',
      'San Jacinto',
      'Ipala',
    ],
    'El Progreso': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE EL PROGRESO
      'Guastatoya',
      'Morazán',
      'San Agustín Acasaguastlán',
      'San Cristóbal Acasaguastlán',
      'El Jícaro',
      'Sansare',
      'Sanarate',
      'San Antonio La Paz',
    ],
    'El Petén': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE EL PETÉN
      'Flores',
      'San Benito',
      'San Andrés',
      'La Libertad',
      'San Francisco',
      'Santa Ana',
      'Dolores',
      'San Luis',
      'Sayaxché',
      'Melchor de Mencos',
      'Poptún',
      'Las Cruces',
      'El Chal',
      'San José',
    ],
    'Escuintla': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE ESCUINTLA
      'Escuintla',
      'Santa Lucía Cotzumalguapa',
      'La Democracia',
      'Siquinalá',
      'Masagua',
      'Tiquisate',
      'La Gomera',
      'Guanagazapa',
      'San José',
      'Iztapa',
      'Palín',
      'San Vicente Pacaya',
      'Nueva Concepción',
    ],
    'Huehuetenango': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE HUEHUETENANGO
      'Huehuetenango',
      'Chiantla',
      'Malacatancito',
      'Cuilco',
      'Nentón',
      'San Pedro Necta',
      'Jacaltenango',
      'Soloma',
      'Ixtahuacán',
      'Santa Bárbara',
      'La Libertad',
      'La Democracia',
      'San Miguel Acatán',
      'San Rafael La Independencia',
      'Todos Santos Cuchumatán',
      'San Juan Atitán',
      'Santa Eulalia',
      'San Mateo Ixtatán',
      'Colotenango',
      'San Sebastián Huehuetenango',
      'Tectitán',
      'Concepción Huista',
      'San Juan Ixcoy',
      'San Antonio Huista',
      'San Sebastián Coatán',
      'Santa Cruz Barillas',
      'Aguacatán',
      'San Rafael Petzal',
      'San Gaspar Ixchil',
      'Santiago Chimaltenango',
      'Santa Ana Huista',
      'Unión Cantinil',
      'San Pedro Soloma',
    ],
    'Izabal': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE IZABAL
      'Puerto Barrios',
      'Livingston',
      'El Estor',
      'Morales',
      'Los Amates',
    ],
    'Jalapa': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE JALAPA
      'Jalapa',
      'San Pedro Pinula',
      'San Luis Jilotepeque',
      'San Manuel Chaparrón',
      'San Carlos Alzatate',
      'Monjas',
      'Mataquescuintla',
    ],
    'Jutiapa': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE JUTIAPA
      'Jutiapa',
      'El Progreso',
      'Santa Catarina Mita',
      'Agua Blanca',
      'Asunción Mita',
      'Yupiltepeque',
      'Atescatempa',
      'Jerez',
      'El Adelanto',
      'Zapotitlán',
      'Comapa',
      'Jalpatagua',
      'Conguaco',
      'Moyuta',
      'Pasaco',
      'San José Acatempa',
      'Quesada',
    ],
    'Quetzaltenango': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE QUETZALTENANGO
      'Quetzaltenango',
      'Salcajá',
      'Olintepeque',
      'San Carlos Sija',
      'Sibilia',
      'Cabricán',
      'Cajolá',
      'San Miguel Sigüilá',
      'Ocos',
      'San Juan Ostuncalco',
      'San Mateo',
      'Concepción Chiquirichapa',
      'San Martín Sacatepéquez',
      'Almolonga',
      'Cantel',
      'Huitán',
      'Zunil',
      'Colomba Costa Cuca',
      'San Francisco La Unión',
      'El Palmar',
      'Coatepeque',
      'Génova',
      'Flores Costa Cuca',
      'La Esperanza',
    ],
    'Quiché': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE QUICHÉ
      'Santa Cruz del Quiché',
      'Chiché',
      'Chinique',
      'Zacualpa',
      'Chajul',
      'Santo Tomás Chichicastenango',
      'Patzité',
      'San Antonio Ilotenango',
      'San Pedro Jocopilas',
      'Cunen',
      'San Juan Cotzal',
      'Joyabaj',
      'Nebaj',
      'San Andrés Sajcabajá',
      'Uspantán',
      'Sacapulas',
      'San Bartolomé Jocotenango',
      'Canillá',
      'Chicamán',
      'Ixcán',
      'Playa Grande',
    ],
    'Retalhuleu': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE RETALHULEU
      'Retalhuleu',
      'San Sebastián',
      'Santa Cruz Muluá',
      'San Martín Zapotitlán',
      'San Felipe',
      'San Andrés Villa Seca',
      'Champerico',
      'Nuevo San Carlos',
      'El Asintal',
    ],
    'Sacatepéquez': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE SACATEPÉQUEZ
      'Antigua Guatemala',
      'Jocotenango',
      'Pastores',
      'Sumpango',
      'Santiago Sacatepéquez',
      'San Bartolomé Milpas Altas',
      'San Lucas Sacatepéquez',
      'Santa Lucía Milpas Altas',
      'Magdalena Milpas Altas',
      'Santa María de Jesús',
      'Ciudad Vieja',
      'San Miguel Dueñas',
      'Alotenango',
      'San Antonio Aguas Calientes',
      'Santa Catarina Barahona',
      'San Juan Alotenango',
    ],
    'San Marcos': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE SAN MARCOS
      'San Marcos',
      'San Pedro Sacatepéquez',
      'San Antonio Sacatepéquez',
      'Comitancillo',
      'San Miguel Ixtahuacán',
      'Concepción Tutuapa',
      'Tacaná',
      'Sibinal',
      'Tajumulco',
      'Tejutla',
      'San Rafael Pie de la Cuesta',
      'Nuevo Progreso',
      'El Tumbador',
      'San José El Rodeo',
      'Malacatán',
      'Catarina',
      'Ayutla (Tecún Umán)',
      'Ocós',
      'San Pablo',
      'El Quetzal',
      'La Reforma',
      'Pajapita',
      'Ixchiguán',
      'San José Ojetenam',
      'San Cristóbal Cucho',
      'Sipacapa',
      'Esquipulas Palo Gordo',
      'Río Blanco',
      'San Lorenzo',
      'La Blanca',
    ],
    'Santa Rosa': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE SANTA ROSA
      'Cuilapa',
      'Barberena',
      'Santa Rosa de Lima',
      'Casillas',
      'San Rafael Las Flores',
      'Oratorio',
      'San Juan Tecuaco',
      'Chiquimulilla',
      'Taxisco',
      'Santa María Ixhuatán',
      'Guazacapán',
      'Santa Cruz Naranjo',
      'Pueblo Nuevo Viñas',
      'Nueva Santa Rosa',
    ],
    'Sololá': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE SOLOLÁ
      'Sololá',
      'Concepción',
      'Nahualá',
      'Santa Catarina Ixtahuacán',
      'Santa María Visitación',
      'Santa Lucía Utatlán',
      'San Andrés Semetabaj',
      'Panajachel',
      'Santa Catarina Palopó',
      'San Antonio Palopó',
      'San Lucas Tolimán',
      'Santa Cruz La Laguna',
      'San Pablo La Laguna',
      'San Juan La Laguna',
      'San Marcos La Laguna',
      'San Pedro La Laguna',
      'Santiago Atitlán',
      'San José Chacayá',
      'Santa Clara La Laguna',
    ],
    'Suchitepéquez': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE SUCHITEPÉQUEZ
      'Mazatenango',
      'Cuyotenango',
      'San Francisco Zapotitlán',
      'San Bernardino',
      'San José El Ídolo',
      'Santo Domingo Suchitepéquez',
      'San Lorenzo',
      'Samayac',
      'San Pablo Jocopilas',
      'San Antonio Suchitepéquez',
      'San Miguel Panán',
      'San Gabriel',
      'Chicacao',
      'Patulul',
      'Santa Bárbara',
      'San Juan Bautista',
      'Santo Tomás La Unión',
      'Zunilito',
      'Pueblo Nuevo',
      'Río Bravo',
      'San José La Máquina',
    ],
    'Totonicapán': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE TOTONICAPÁN
      'Totonicapán',
      'San Cristóbal Totonicapán',
      'San Francisco El Alto',
      'San Andrés Xecul',
      'Momostenango',
      'Santa María Chiquimula',
      'Santa Lucía La Reforma',
      'San Bartolo',
    ],
    'Zacapa': [
      // AQUÍ AGREGAS LOS MUNICIPIOS DE ZACAPA
      'Zacapa',
      'Estanzuela',
      'Río Hondo',
      'Gualán',
      'Teculután',
      'Usumatlán',
      'Cabañas',
      'San Diego',
      'La Unión',
      'Huité',
      'San Jorge',
    ],
  };

  // Función helper para obtener municipios de un departamento
  static List<String> obtenerMunicipios(String departamento) {
    return municipiosPorDepartamento[departamento] ?? [];
  }
}
