INSERT INTO municipios (departamento, municipio, alcalde, partido_alcalde) VALUES
('ALTA VERAPAZ', 'CAHABÓN', 'Denis Cristian Fraatz Sierra', 'VAMOS'),
('ALTA VERAPAZ', 'CHAHAL', 'Luis Rodolfo Barrientos Figueroa', 'AZUL'),
('ALTA VERAPAZ', 'CHISEC', 'Fidencio Lima Pop', 'VAMOS'),
('ALTA VERAPAZ', 'COBÁN', 'Felipe Antonio Pop Cucul', 'CABAL'),
('ALTA VERAPAZ', 'FRAY BARTOLOMÉ DE LAS CASAS', 'Arnoldo Federico Fontana Hercules', 'UNE'),
('ALTA VERAPAZ', 'LANQUÍN', 'Edin Rolando Pop Choc', 'UNE'),
('ALTA VERAPAZ', 'PANZÓS', 'Ernesto Ramirez Caal', 'VAMOS'),
('ALTA VERAPAZ', 'RAXRUHÁ', 'Carlos Tut Xol', 'VAMOS'),
('ALTA VERAPAZ', 'SAN CRISTÓBAL VERAPAZ', 'Edgar Rolando Chocoy Sierra', 'UNE'),
('ALTA VERAPAZ', 'SAN JUAN CHAMELCO', 'Álvaro García', 'VAMOS'),
('ALTA VERAPAZ', 'SAN PEDRO CARCHÁ', 'Erwin Catún Maquin', 'UNE'),
('ALTA VERAPAZ', 'SANTA CATALINA LA TINTA', 'Horacio Oswaldo Mendoza Fernández', 'VAMOS'),
('ALTA VERAPAZ', 'SANTA CRUZ VERAPAZ', 'Roberto Arnoldo Jucub Valdéz', 'VAMOS'),
('ALTA VERAPAZ', 'SENAHÚ', 'Rolando Maquín Caal', 'NOSOTROS'),
('ALTA VERAPAZ', 'TACTIC', 'Edin Rolando Guerrero Guerrero', 'UNE'),
('ALTA VERAPAZ', 'TAMAHÚ', 'Eduardo Moll Santa Cruz', 'VALOR'),
('ALTA VERAPAZ', 'TUCURÚ', 'Leonel Victoriano Guzman Argueta', 'VAMOS'),
('BAJA VERAPAZ', 'CUBULCO', 'Tomas Marcelino Alonzo Teletor', 'VAMOS'),
('BAJA VERAPAZ', 'EL CHOL', 'Enrique Milian Perez', 'VAMOS'),
('BAJA VERAPAZ', 'GRANADOS', 'Marvin Ovidio Canahui Marroquin', 'VAMOS'),
('BAJA VERAPAZ', 'PURULHÁ', 'Edgar Xoy', 'VALOR'),
('BAJA VERAPAZ', 'RABINAL', 'José Octaviano Alvarado García', 'CABAL'),
('BAJA VERAPAZ', 'SALAMÁ', 'Victor Jordan De La Cruz Cruz', 'VAMOS'),
('BAJA VERAPAZ', 'SAN JERÓNIMO', 'Gilberto Salomon Lopez Alcantara', 'VAMOS'),
('BAJA VERAPAZ', 'SAN MIGUEL CHICAJ', 'Fernando Calate Cuquej', 'VAMOS'),
('CHIMALTENANGO', 'ACATENANGO', 'Werner Abedamar Marroquín Cabrera', 'VAMOS'),
('CHIMALTENANGO', 'CHIMALTENANGO', 'Alfonso Elel Castro', 'Comité Cívico CH''ICH'),
('CHIMALTENANGO', 'COMALAPA', 'Justo Rufino Similox Pichiya', 'VAMOS'),
('CHIMALTENANGO', 'EL TEJAR', 'Julio Axel Figueroa Muñoz', 'VAMOS'),
('CHIMALTENANGO', 'PARRAMOS', 'Amílcar Suy Cubul', 'CABAL'),
('CHIMALTENANGO', 'PATZICÍA', 'Sergio Eleazar Esquit Can', 'Comité Cívico Electoral Samajel'),
('CHIMALTENANGO', 'PATZÚN', 'Guadalupe Cojti Xulu', 'VAMOS'),
('CHIMALTENANGO', 'POCHUTA', 'Lester Joel García Guerrero', 'VALOR'),
('CHIMALTENANGO', 'SAN ANDRÉS ITZAPA', 'José Denis Azurdia Pichol', 'UNIONISTA'),
('CHIMALTENANGO', 'SAN JOSÉ POAQUIL', 'Juan Aroldo Santelel Sisimit', 'CABAL'),
('CHIMALTENANGO', 'SAN MARTÍN JILOTEPEQUE', 'Marvin Yovany Aguín Aguín', 'TODOS'),
('CHIMALTENANGO', 'SANTA APOLONIA', 'Selvin Carlos Pinzón de la Cruz', 'UNIONISTA'),
('CHIMALTENANGO', 'SANTA CRUZ BALANYÁ', 'Enio Oswaldo Juárez Roquel', 'VAMOS'),
('CHIMALTENANGO', 'TECPÁN GUATEMALA', 'Flaviano Salomón Díaz', 'VAMOS'),
('CHIMALTENANGO', 'YEPOCAPA', 'Bernabe Ajin Vicente', 'VAMOS'),
('CHIMALTENANGO', 'ZARAGOZA', 'Julio Roberto Girón Porras', 'UNE'),
('CHIQUIMULA', 'CAMOTÁN', 'Noe Rolando Guerra Guerra', 'VAMOS'),
('CHIQUIMULA', 'CHIQUIMULA', 'José René Pinto España', 'VAMOS'),
('CHIQUIMULA', 'CONCEPCIÓN LAS MINAS', 'Juan Antonio Vanegas Hernández', 'VAMOS'),
('CHIQUIMULA', 'ESQUIPULAS', 'Carlos Alberto Portillo Palma', 'VALOR'),
('CHIQUIMULA', 'IPALA', 'Lusvin Javier Javier', 'CAMBIO'),
('CHIQUIMULA', 'JOCOTÁN', 'Ramón Díaz Gutiérrez', 'VAMOS'),
('CHIQUIMULA', 'OLOPA', 'Oscar Medardo Cardona Noguera', 'VAMOS'),
('CHIQUIMULA', 'QUEZALTEPEQUE', 'Milton Rolando Morales Duarte', 'VAMOS'),
('CHIQUIMULA', 'SAN JACINTO', 'Marvin Juventino Morales Palma', 'VAMOS'),
('CHIQUIMULA', 'SAN JOSÉ LA ARADA', 'Melvin Licinio León Villeda', 'VAMOS'),
('CHIQUIMULA', 'SAN JUAN ERMITA', 'Miguel Ángel López Gutiérrez', 'VAMOS'),
('EL PROGRESO', 'EL JÍCARO', 'José Francisco Mejía Flores', 'VAMOS'),
('EL PROGRESO', 'GUASTATOYA', 'José Elías Herrera Guerra', 'VALOR'),
('EL PROGRESO', 'MORAZÁN', 'Marco Tulio Arriaza Cordova', 'VAMOS'),
('EL PROGRESO', 'SAN AGUSTÍN ACASAGUASTLÁN', 'Byron Manolo Aguilar Aldana', 'VAMOS'),
('EL PROGRESO', 'SAN ANTONIO LA PAZ', 'Nubere Agustín Lopez Lopez', 'VAMOS'),
('EL PROGRESO', 'SAN CRISTÓBAL ACASAGUASTLÁN', 'Edgar Humberto Castañeda Ruano', 'VAMOS'),
('EL PROGRESO', 'SANARATE', 'César Augusto Rodas Álvarez', 'VAMOS'),
('EL PROGRESO', 'SANSARE', 'Sebastián Morales Carrera', 'VAMOS'),
('ESCUINTLA', 'ESCUINTLA', 'Edgar Abraham Rivera Estevez', 'VICTORIA'),
('ESCUINTLA', 'GUANAGAZAPA', 'Weimer Wuilfredo Reyes Castillo', 'VAMOS'),
('ESCUINTLA', 'IZTAPA', 'Jonatan Josué Zarceño Cortés', 'VALOR'),
('ESCUINTLA', 'LA DEMOCRACIA', 'Juan Ramiro Soto García', 'UNE'),
('ESCUINTLA', 'LA GOMERA', 'Héctor Hugo Cardona Morales', 'VAMOS'),
('ESCUINTLA', 'MASAGUA', 'Nelson Luciano Marroquín Marroquín', 'VAMOS'),
('ESCUINTLA', 'NUEVA CONCEPCIÓN', 'Isaías Corado García', 'UNE'),
('ESCUINTLA', 'PALÍN', 'Byron Ranulfo Rustrián Amado', 'UNE'),
('ESCUINTLA', 'SAN JOSÉ', 'Odilia González García de Rizzo', 'VALOR'),
('ESCUINTLA', 'SAN VICENTE PACAYA', 'Axel Catalino Gonzalez', 'VAMOS'),
('ESCUINTLA', 'SANTA LUCÍA COTZUMALGUAPA', 'Julio Armando Espinoza Paz', 'VAMOS'),
('ESCUINTLA', 'SIPACATE', 'Walter Orlando Najera González', 'VALOR'),
('ESCUINTLA', 'SIQUINALÁ', 'Daniel González Jiménez', 'CABAL'),
('ESCUINTLA', 'TIQUISATE', 'Héctor Hipólito Cifuentes Ruano', 'CABAL'),
('GUATEMALA', 'AMATITLÁN', 'Mainor Guillermo Orellana', 'VALOR'),
('GUATEMALA', 'CHINAUTLA', 'Brenda Elizabeth Del Cid Medrano', 'VAMOS'),
('GUATEMALA', 'CHUARRANCHO', 'Gerson Saul Ajcuc Xot', 'VAMOS'),
('GUATEMALA', 'FRAIJANES', 'Daniel Rustrián', 'VALOR'),
('GUATEMALA', 'GUATEMALA', 'Ricardo Quiñónez Lemus', 'VALOR-UNIONISTA'),
('GUATEMALA', 'MIXCO', 'Neto Bran Montenegro', 'PPG'),
('GUATEMALA', 'PALENCIA', 'Guadalupe Alberto Reyes Aguilar', 'VAMOS'),
('GUATEMALA', 'PETAPA', 'Mynor Rolando Morales Chávez', 'VALOR'),
('GUATEMALA', 'SAN JOSÉ DEL GOLFO', 'Yessica Palencia', 'UNE'),
('GUATEMALA', 'SAN JOSÉ PINULA', 'Johnny Frederyk Ayala Toledo', 'CABAL'),
('GUATEMALA', 'SAN JUAN SACATEPÉQUEZ', 'Juan Carlos Pellecer Agustín', 'VAMOS'),
('GUATEMALA', 'SAN PEDRO AYAMPUC', 'Nelvi Elidi Quiñonez Morales', 'CABAL'),
('GUATEMALA', 'SAN PEDRO SACATEPÉQUEZ', 'Juan Leonel Culajay Pérez', 'VIVA'),
('GUATEMALA', 'SAN RAIMUNDO', 'Florentín Luis Álvaro Queche Sarceño', 'Desarrollo San Raymundense'),
('GUATEMALA', 'SANTA CATARINA PINULA', 'Sebastián Siero Asturias', 'VALOR-UNIONISTA'),
('GUATEMALA', 'VILLA CANALES', 'Ramiro Rivera', 'VALOR'),
('GUATEMALA', 'VILLA NUEVA', 'Mynor Morales Zurita', 'VALOR'),
('HUEHUETENANGO', 'AGUACATÁN', 'Pablo Escobar Méndez', 'VAMOS'),
('HUEHUETENANGO', 'BARILLAS', 'Gilberto Francisco Manuel', 'CABAL'),
('HUEHUETENANGO', 'CHIANTLA', 'Elvis Gilberto Tello Alvarado', 'VAMOS'),
('HUEHUETENANGO', 'COLOTENANGO', 'Romeo Domingo Gómez', 'VAMOS'),
('HUEHUETENANGO', 'CONCEPCIÓN HUISTA', 'Juan Ahilon Vargas', 'CABAL'),
('HUEHUETENANGO', 'CUILCO', 'Audilio Epifanio Roblero Arreaga', 'URNG MAIZ'),
('HUEHUETENANGO', 'HUEHUETENANGO', 'Gustavo Adolfo Cano Villatoro', 'VAMOS'),
('HUEHUETENANGO', 'IXTAHUACÁN', 'Elías Ortiz Andrés', 'VAMOS'),
('HUEHUETENANGO', 'JACALTENANGO', 'Juan Antonio Camposeco Delgado', 'CABAL'),
('HUEHUETENANGO', 'LA DEMOCRACIA', 'Santiago Aminadab Molina López', 'VAMOS'),
('HUEHUETENANGO', 'LA LIBERTAD', 'Oscar Armindo Pérez', 'CABAL'),
('HUEHUETENANGO', 'MALACATANCITO', 'Irma Elizabeth Ávila Alvarado', 'VAMOS'),
('HUEHUETENANGO', 'NENTÓN', 'Rudi Gordillo Velasco', 'VAMOS'),
('HUEHUETENANGO', 'PETATÁN', 'Juan Bernardo Hernandez Domingo', 'VAMOS'),
('HUEHUETENANGO', 'SAN ANTONIO HUISTA', 'Lindin Marin Morales Saenz', 'VAMOS'),
('HUEHUETENANGO', 'SAN GASPAR IXCHIL', 'Sebastián García Pérez', 'VAMOS'),
('HUEHUETENANGO', 'SAN JUAN ATITÁN', 'Santos Hernández Godinez', 'CABAL'),
('HUEHUETENANGO', 'SAN JUAN IXCOY', 'Andrés Rafael López', 'VAMOS'),
('HUEHUETENANGO', 'SAN MATEO IXTATÁN', 'Andres Santizo Gómez', 'VAMOS'),
('HUEHUETENANGO', 'SAN MIGUEL ACATÁN', 'Miguel Alonzo Carlos', 'UNE'),
('HUEHUETENANGO', 'SAN PEDRO NECTA', 'Julio Amilcar Ambrocio Ramírez', 'VAMOS'),
('HUEHUETENANGO', 'SAN RAFAEL LA INDEPENDENCIA', 'Emilio Francisco Andrés', 'CABAL'),
('HUEHUETENANGO', 'SAN RAFAEL PETZAL', 'Kalinery Morales Sales', 'CABAL'),
('HUEHUETENANGO', 'SAN SEBASTIÁN COATÁN', 'Juan Sebastian Diego Juan', 'VAMOS'),
('HUEHUETENANGO', 'SAN SEBASTIÁN HUEHUETENANGO', 'Rigoberto Sales Sales', 'VAMOS'),
('HUEHUETENANGO', 'SANTA ANA HUISTA', 'Edin Morales Figueroa', 'VAMOS'),
('HUEHUETENANGO', 'SANTA BÁRBARA', 'Efraín López Gómez', 'VAMOS'),
('HUEHUETENANGO', 'SANTA EULALIA', 'Augusto Sebastián Francisquez Pérez', 'CABAL'),
('HUEHUETENANGO', 'SANTIAGO CHIMALTENANGO', 'Froylan Elias Aguilar Jiménez', 'VAMOS'),
('HUEHUETENANGO', 'SOLOMA', 'Felipe Domingo Bacilio Pedro', 'CABAL'),
('HUEHUETENANGO', 'TECTITÁN', 'Dony Rossembert Angel Borrayes', 'VAMOS'),
('HUEHUETENANGO', 'TODOS SANTOS CUCHUMATÁN', 'Martin Jiménez Jerónimo', 'VAMOS'),
('HUEHUETENANGO', 'UNIÓN CANTINIL', 'Osmar Alexander Tello Figueroa', 'VAMOS'),
('IZABAL', 'EL ESTOR', 'Enrique Edmundo Cuc Caal', 'VAMOS'),
('IZABAL', 'LOS AMATES', 'Miguel Alonzo Barrientos', 'CABAL'),
('IZABAL', 'LÍVINGSTON', 'Enrique Edmundo Zaldaña Altan', 'CABAL'),
('IZABAL', 'MORALES', 'Maynor David Portillo Vásquez', 'VAMOS'),
('IZABAL', 'PUERTO BARRIOS', 'Hugo Rene Sarceño Orellana', 'VAMOS'),
('JALAPA', 'JALAPA', 'Omar Camposeco', 'CABAL'),
('JALAPA', 'MATAQUESCUINTLA', 'Hector Felipe Guevara Pineda', 'UNE'),
('JALAPA', 'MONJAS', 'Juan Antonio Orellana Cardona', 'VAMOS'),
('JALAPA', 'SAN CARLOS ALZATATE', 'Fredi Omar García Galiano', 'VAMOS'),
('JALAPA', 'SAN LUIS JILOTEPEQUE', 'Juan de la Cruz Felipe Damián', 'VAMOS'),
('JALAPA', 'SAN MANUEL CHAPARRÓN', 'Ricardo Alberto Sandoval Noriega', 'VAMOS'),
('JALAPA', 'SAN PEDRO PINULA', 'José Roberto Ramírez Guerra', 'VAMOS'),
('JUTIAPA', 'AGUA BLANCA', 'Julio César Guerra Cameros', 'PHG'),
('JUTIAPA', 'ASUNCIÓN MITA', 'Francisco Guardado Lemus', 'VAMOS'),
('JUTIAPA', 'ATESCATEMPA', 'José Mauricio Contreras Morán', 'VAMOS'),
('JUTIAPA', 'COMAPA', 'Cesar Estuardo Vasquez Recinos', 'VAMOS'),
('JUTIAPA', 'CONGUACO', 'Manuel González', 'CABAL'),
('JUTIAPA', 'EL ADELANTO', 'Teofilo Sinohe Corado Azmitia', 'VAMOS'),
('JUTIAPA', 'EL PROGRESO', 'Marvin Enrique Zepeda González', 'VAMOS'),
('JUTIAPA', 'JALPATAGUA', 'Gustavo Adolfo Recinos Corea', 'AZUL'),
('JUTIAPA', 'JEREZ', 'Carlos Efraín Melgar Torres', 'VAMOS'),
('JUTIAPA', 'JUTIAPA', 'Cesar Estuardo Paredes Pérez', 'CABAL'),
('JUTIAPA', 'MOYUTA', 'Carlos Roberto Marroquin Fuentes', 'VAMOS'),
('JUTIAPA', 'PASACO', 'Ottoniel Pineda Herrera', 'VAMOS'),
('JUTIAPA', 'QUESADA', 'Carlos Alberto Martínez Castellanos', 'VAMOS'),
('JUTIAPA', 'SAN JOSÉ ACATEMPA', 'Esteban Adolfo Castillo Y Castillo', 'VAMOS'),
('JUTIAPA', 'SANTA CATARINA MITA', 'William Geovanny Duarte Aguilar', 'VAMOS'),
('JUTIAPA', 'YUPILTEPEQUE', 'Carlos Aníbal Godoy Torres', 'VAMOS'),
('JUTIAPA', 'ZAPOTITLÁN', 'Hilmar Edgardo Quiñonez Y Quiñonez', 'VAMOS'),
('PETÉN', 'DOLORES', 'Marvin Rolando Cruz Guzman', 'VAMOS'),
('PETÉN', 'EL CHAL', 'Elías Calderón Álvarez', 'VAMOS'),
('PETÉN', 'FLORES', 'Ramón Humberto Méndez Cabrera', 'UNE'),
('PETÉN', 'LA LIBERTAD', 'Yony Maldonado Calderón', 'CABAL'),
('PETÉN', 'LAS CRUCES', 'Bayron Bernal Oliva', 'VAMOS'),
('PETÉN', 'MELCHOR DE MENCOS', 'Jorge Dominguez', 'VIVA'),
('PETÉN', 'POPTÚN', 'Salvador Hernández Rosado', 'NOSOTROS'),
('PETÉN', 'SAN ANDRÉS', 'Jonne Méndez Bardales', 'VAMOS'),
('PETÉN', 'SAN BENITO', 'Carlos Antonio Kuylen Morales', 'VAMOS'),
('PETÉN', 'SAN FRANCISCO', 'Juan José Paredes Guzman', 'VAMOS'),
('PETÉN', 'SAN JOSÉ', 'Yobani Donaldo Cortez Zac', 'VAMOS'),
('PETÉN', 'SAN LUIS', 'Efraín Oliva Muralles', 'VAMOS'),
('PETÉN', 'SANTA ANA', 'Cesar Augusto Garrido Rosado', 'VAMOS'),
('PETÉN', 'SAYAXCHÉ', 'Eduardo Ayala', 'VAMOS'),
('QUETZALTENANGO', 'ALMOLONGA', 'Oscar Paul Gonon Nimatuj', 'VAMOS'),
('QUETZALTENANGO', 'CABRICÁN', 'Gilder Edilzar Delgado López', 'VAMOS'),
('QUETZALTENANGO', 'CAJOLÁ', 'Juan Gomez Lopez', 'VAMOS'),
('QUETZALTENANGO', 'CANTEL', 'Alan Cabrera Cabrera', 'UNE'),
('QUETZALTENANGO', 'COATEPEQUE', 'Alfonso García Junco Hemmerling', 'VAMOS'),
('QUETZALTENANGO', 'COLOMBA', 'Isidro Herminio Castillo Díaz', 'VAMOS'),
('QUETZALTENANGO', 'CONCEPCIÓN CHIQUIRICHAPA', 'Remigio Hernandez Lorenzo', 'VAMOS'),
('QUETZALTENANGO', 'EL PALMAR', 'Rene Haroldo Ramírez Méndez', 'CABAL'),
('QUETZALTENANGO', 'FLORES COSTA CUCA', 'Mario Rene Lozano Giron', 'VAMOS'),
('QUETZALTENANGO', 'GÉNOVA', 'Amilcar Escalante Morales', 'VAMOS'),
('QUETZALTENANGO', 'HUITÁN', 'Cesar Augusto Calderón López', 'VAMOS'),
('QUETZALTENANGO', 'LA ESPERANZA', 'Armando Ixtabalán Gómez', 'CABAL'),
('QUETZALTENANGO', 'OLINTEPEQUE', 'Carlos Enrique Baten Gomez', 'CABAL'),
('QUETZALTENANGO', 'OSTUNCALCO', 'Felix Luis Marroquin Escalante', 'VAMOS'),
('QUETZALTENANGO', 'PALESTINA DE LOS ALTOS', 'Arnoldo Ruperto Castillo Contreras', 'SEMILLA'),
('QUETZALTENANGO', 'QUETZALTENANGO', 'Juan Fernando López', 'PHG'),
('QUETZALTENANGO', 'SALCAJÁ', 'William Rodolfo Calderón López', 'VAMOS'),
('QUETZALTENANGO', 'SAN CARLOS SIJA', 'Hugo Arlando García Mazariegos', 'VAMOS'),
('QUETZALTENANGO', 'SAN FRANCISCO LA UNIÓN', 'Francisco González Matul', 'URNG MAIZ'),
('QUETZALTENANGO', 'SAN MARTÍN SACATEPÉQUEZ', 'Juan De Leon Salez', 'VAMOS'),
('QUETZALTENANGO', 'SAN MATEO', 'Elvin Yobany Cifuentes Escobar', 'CABAL'),
('QUETZALTENANGO', 'SAN MIGUEL SIGÜILÁ', 'Aníbal Diaz Vicente', 'VAMOS'),
('QUETZALTENANGO', 'SIBILIA', 'Gelver Facundo Ochoa Gramajo', 'VAMOS'),
('QUETZALTENANGO', 'ZUNIL', 'Bernabé Mateo Civay Huix', 'WINAQ'),
('QUICHÉ', 'CANILLÁ', 'Yanuario Urizar Anzueto', 'VAMOS'),
('QUICHÉ', 'CHAJUL', 'Juan Mateo Bop', 'VAMOS'),
('QUICHÉ', 'CHICAMÁN', 'Pedro Gamarro Morales', 'VAMOS'),
('QUICHÉ', 'CHICHICASTENANGO', 'Manuel Tebelan Calgua', 'VAMOS'),
('QUICHÉ', 'CHICHÉ', 'Mario Frederick Tiño Lindo', 'VAMOS'),
('QUICHÉ', 'CHINIQUE', 'Mayrol Gregorio Juárez Pérez', 'VAMOS'),
('QUICHÉ', 'CUNÉN', 'Pedro Alejandro Pu Canto', 'VAMOS'),
('QUICHÉ', 'IXCÁN', 'Antonio Elias Calel', 'VAMOS'),
('QUICHÉ', 'JOYABAJ', 'Florencio Carrascoza Gamez', 'VAMOS'),
('QUICHÉ', 'NEBAJ', 'Virgilio Geronimo Bernal Guzmán', 'VAMOS'),
('QUICHÉ', 'PACHALUM', 'Boanerges Velasquez Duarte', 'VAMOS'),
('QUICHÉ', 'PATZITÉ', 'Melchor Aguare Calel', 'VAMOS'),
('QUICHÉ', 'SACAPULAS', 'Alberto Lux Tzunux', 'VAMOS'),
('QUICHÉ', 'SAN ANDRÉS SAJCABAJÁ', 'Pedro Tix Gonzales', 'VAMOS'),
('QUICHÉ', 'SAN ANTONIO ILOTENANGO', 'Domingo Ajeataz Cho', 'VAMOS'),
('QUICHÉ', 'SAN BARTOLOMÉ JOCOTENANGO', 'Joaquin Xotoy Tum', 'VAMOS'),
('QUICHÉ', 'SAN JUAN COTZAL', 'Jacinto Sambrano Medina', 'VALOR'),
('QUICHÉ', 'SAN PEDRO JOCOPILAS', 'Nicolas López Mendoza', 'VAMOS'),
('QUICHÉ', 'SANTA CRUZ DEL QUICHÉ', 'Nery Alfonso Ramírez Revolorio', 'VAMOS'),
('QUICHÉ', 'USPANTÁN', 'Victor Hugo Figueroa Perez', 'CABAL'),
('QUICHÉ', 'ZACUALPA', 'Sabino Herwin Calachij Gutierrez', 'VAMOS'),
('RETALHULEU', 'CHAMPERICO', 'César Augusto Marroquín Cruz', 'CABAL'),
('RETALHULEU', 'EL ASINTAL', 'Hugo Ranferi Escobar Barrios', 'VAMOS'),
('RETALHULEU', 'NUEVO SAN CARLOS', 'Pascual de León de León', 'CABAL'),
('RETALHULEU', 'RETALHULEU', 'Pablo José Villatoro Flores', 'CABAL'),
('RETALHULEU', 'SAN ANDRÉS VILLA SECA', 'Marco Tulio De Leon Solares', 'VAMOS'),
('RETALHULEU', 'SAN FELIPE', 'Adonias Jehu Salazar Quezada', 'VAMOS'),
('RETALHULEU', 'SAN MARTÍN ZAPOTITLÁN', 'Blanca Estela Mendoza Méndez', 'VAMOS'),
('RETALHULEU', 'SAN SEBASTIÁN', 'Oscar David Taleon Alban', 'VAMOS'),
('RETALHULEU', 'SANTA CRUZ MULUÁ', 'Elio Francisco Puac Castillo', 'VAMOS'),
('SACATEPÉQUEZ', 'ALOTENANGO', 'Sergio Gonzalo Sul Civil', 'ELEFANTE'),
('SACATEPÉQUEZ', 'ANTIGUA GUATEMALA', 'Juan Manuel Asturias Sueras', 'C.C. Futuro'),
('SACATEPÉQUEZ', 'CIUDAD VIEJA', 'Clemente Federico Arturo Bethancourt Sánchez', 'Libre Ciudad Vieja'),
('SACATEPÉQUEZ', 'JOCOTENANGO', 'Gerald Iván Meoño Rodas', 'CABAL'),
('SACATEPÉQUEZ', 'MAGDALENA MILPAS ALTAS', 'Erick Noel Martínez López', 'CABAL'),
('SACATEPÉQUEZ', 'PASTORES', 'José Lizandro Zamora Chamalé', 'CABAL'),
('SACATEPÉQUEZ', 'SAN ANTONIO AGUAS CALIENTES', 'Aldo Normando López Mican', 'VOS'),
('SACATEPÉQUEZ', 'SAN BARTOLOMÉ MILPAS ALTAS', 'Ruben Ernesto Axpuac Velasquez', 'CABAL'),
('SACATEPÉQUEZ', 'SAN LUCAS SACATEPÉQUEZ', 'Yener Haroldo Plaza Natareno', 'UNE'),
('SACATEPÉQUEZ', 'SAN MIGUEL DUEÑAS', 'Eduardo Morales Medio', 'VAMOS'),
('SACATEPÉQUEZ', 'SANTA CATARINA BARAHONA', 'Elmer Neftali Ordoñez López', 'CC Somos Santa Catarina'),
('SACATEPÉQUEZ', 'SANTA LUCÍA MILPAS ALTAS', 'Luis Orlando Guerra Oliva', 'CABAL'),
('SACATEPÉQUEZ', 'SANTA MARÍA DE JESÚS', 'Mario Jerónimo Pérez Pp', 'NOSOTROS'),
('SACATEPÉQUEZ', 'SANTIAGO SACATEPÉQUEZ', 'Manuel Augusto Navas y Navas', 'TODOS'),
('SACATEPÉQUEZ', 'SANTO DOMINGO XENACOJ', 'David Aniceto Aquino Chocoyo', 'CABAL'),
('SACATEPÉQUEZ', 'SUMPANGO', 'Carlos Enrique Cubur Sula', 'C.C. Somos Sumpango'),
('SAN MARCOS', 'AYUTLA', 'Isel Aneli Suñiga Morfín', 'Comité Cívico Crecer (CCC)'),
('SAN MARCOS', 'CATARINA', 'Luis Alberto Mendoza Barrios', 'CREO'),
('SAN MARCOS', 'COMITANCILLO', 'Carlos Enrique López Agustín', 'VAMOS'),
('SAN MARCOS', 'CONCEPCIÓN TUTUAPA', 'Ofelio Joel Morales Simon', 'VAMOS'),
('SAN MARCOS', 'EL QUETZAL', 'Guillermo Amílcar Ambrosy Mazariegos', 'VAMOS'),
('SAN MARCOS', 'EL RODEO', 'Roderico Eleazar Ramos Aguilar', 'VAMOS'),
('SAN MARCOS', 'EL TUMBADOR', 'Juan Carlos López Godínez', 'VAMOS'),
('SAN MARCOS', 'ESQUIPULAS PALO GORDO', 'Exadillas Dionel Ramos Aguilar', 'VAMOS'),
('SAN MARCOS', 'IXCHIGUÁN', 'Mario Alberto Chávez Chávez', 'VAMOS'),
('SAN MARCOS', 'LA BLANCA', 'Edilma Elizabeth Navarijo De León', 'NOSOTROS'),
('SAN MARCOS', 'LA REFORMA', 'Carlos Noel López Mérida', 'VAMOS'),
('SAN MARCOS', 'MALACATÁN', 'Emilio Obdulio Galvez Perez', 'VAMOS'),
('SAN MARCOS', 'NUEVO PROGRESO', 'Aureliano Gonzales Hernández', 'VAMOS'),
('SAN MARCOS', 'OCÓS', 'Álvaro de León de León', 'NOSOTROS'),
('SAN MARCOS', 'PAJAPITA', 'Hilma Florinda López Navarro', 'VAMOS'),
('SAN MARCOS', 'RÍO BLANCO', 'Oscar Tereso Álvarez Abelarde', 'CABAL'),
('SAN MARCOS', 'SAN ANTONIO SACATEPÉQUEZ', 'Óscar Jonathan Pérez Cardona', 'VAMOS'),
('SAN MARCOS', 'SAN CRISTÓBAL CUCHO', 'Osmar Obdulio López Ramírez', 'VAMOS'),
('SAN MARCOS', 'SAN JOSÉ OJETENAM', 'Bayron David Chaj González', 'VAMOS'),
('SAN MARCOS', 'SAN LORENZO', 'Roldan Josue Tema Coronado', 'VAMOS'),
('SAN MARCOS', 'SAN MARCOS', 'Otto Francisco Castillo Bautista', 'TODOS'),
('SAN MARCOS', 'SAN MIGUEL IXTAHUACÁN', 'Jorge Rolando Pérez Domingo', 'VAMOS'),
('SAN MARCOS', 'SAN PABLO', 'Rudy Danilo Martínez Ocaña', 'VAMOS'),
('SAN MARCOS', 'SAN PEDRO SACATEPÉQUEZ', 'Luis Rivera', 'VIVA'),
('SAN MARCOS', 'SAN RAFAEL PIE DE LA CUESTA', 'Over Leonel Reyna Escobar', 'VAMOS'),
('SAN MARCOS', 'SIBINAL', 'Walter Rodrigo Roblero Ortiz', 'VAMOS'),
('SAN MARCOS', 'SIPACAPA', 'Ernesto Ramiro Bautista Rafael', 'CABAL'),
('SAN MARCOS', 'TACANÁ', 'Eulalio Nicacio De Leon Velasquez', 'CABAL'),
('SAN MARCOS', 'TAJUMULCO', 'José Eliseo Chávez Chávez', 'VAMOS'),
('SAN MARCOS', 'TEJUTLA', 'Rafael Humberto Gómez Arreaga', 'VAMOS'),
('SANTA ROSA', 'BARBERENA', 'Jonathan José Antonio Rueda Vallejo', 'VAMOS'),
('SANTA ROSA', 'CASILLAS', 'Dayri Benjamin Bocanegra Salazar', 'VAMOS'),
('SANTA ROSA', 'CHIQUIMULILLA', 'Rubén Dario Escobar Ruiz', 'VAMOS'),
('SANTA ROSA', 'CUILAPA', 'Mariflor Morales', 'VAMOS'),
('SANTA ROSA', 'GUAZACAPÁN', 'Noel de la Cruz Pablo', 'UNE'),
('SANTA ROSA', 'NUEVA SANTA ROSA', 'José Enrique Arredondo Amaya', 'CABAL'),
('SANTA ROSA', 'ORATORIO', 'Nery Armando Castillo Olivares', 'UNE'),
('SANTA ROSA', 'PUEBLO NUEVO VIÑAS', 'Cristiams Josue Blanco Fajardo', 'VAMOS'),
('SANTA ROSA', 'SAN JUAN TECUACO', 'Marvin Morales García', 'UNE'),
('SANTA ROSA', 'SAN RAFAEL LAS FLORES', 'Luis Fernando Monterroso Morales', 'CABAL'),
('SANTA ROSA', 'SANTA CRUZ NARANJO', 'Iván Antonio Morales Del Cid', 'CABAL'),
('SANTA ROSA', 'SANTA MARÍA IXHUATÁN', 'Wilson Antonio González Corado', 'CABAL'),
('SANTA ROSA', 'SANTA ROSA DE LIMA', 'Juan José Dávila Aguilar', 'CABAL'),
('SANTA ROSA', 'TAXISCO', 'Vidal Montepeque Barillas', 'VAMOS'),
('SOLOLÁ', 'CONCEPCIÓN', 'Filiberto Sequec Juracán', 'UNE'),
('SOLOLÁ', 'NAHUALÁ', 'Manuel Guarchaj Tzep', 'VAMOS'),
('SOLOLÁ', 'PANAJACHEL', 'Manuel Zacarías Sahón Rosales', 'MLP'),
('SOLOLÁ', 'SAN ANDRÉS SEMETABAJ', 'Bairon Ricardo Tobías Sánchez', 'VAMOS'),
('SOLOLÁ', 'SAN ANTONIO PALOPÓ', 'Rufino Elfidio Caniz Vicente', 'VAMOS'),
('SOLOLÁ', 'SAN JOSÉ CHACAYÁ', 'Luis Florencio García Chuta', 'VAMOS'),
('SOLOLÁ', 'SAN JUAN LA LAGUNA', 'Francis Daniel Chavajay Herrera', 'VAMOS'),
('SOLOLÁ', 'SAN LUCAS TOLIMÁN', 'Eswin Rolando Buch Tojín', 'VAMOS'),
('SOLOLÁ', 'SAN MARCOS LA LAGUNA', 'Vicente Raúl Puzul Mendoza', 'VAMOS'),
('SOLOLÁ', 'SAN PABLO LA LAGUNA', 'Gaspar Ixcayá Culum', 'VAMOS'),
('SOLOLÁ', 'SAN PEDRO LA LAGUNA', 'Cándida González Chipir de Coroxón', 'VIVA'),
('SOLOLÁ', 'SANTA CATARINA IXTAHUACÁN', 'Pascual Tambriz Tzep', 'VAMOS'),
('SOLOLÁ', 'SANTA CATARINA PALOPÓ', 'Antonio Tax López', 'CABAL'),
('SOLOLÁ', 'SANTA CLARA LA LAGUNA', 'Francisco Chavajay Saquic', 'VAMOS'),
('SOLOLÁ', 'SANTA CRUZ LA LAGUNA', 'Pedro Juan Solís', 'VAMOS'),
('SOLOLÁ', 'SANTA LUCÍA UTATLÁN', 'Stuardo Alfonso Cáceres Ovalle', 'VAMOS'),
('SOLOLÁ', 'SANTA MARÍA VISITACIÓN', 'Mario Roberto Dionisio Dionisio', 'VAMOS'),
('SOLOLÁ', 'SANTIAGO ATITLÁN', 'Francisco Coché Pablo', 'CABAL'),
('SOLOLÁ', 'SOLOLÁ', 'Andrés Lisandro Iboy Chiroy', 'C.C. SUD'),
('SUCHITEPÉQUEZ', 'CHICACAO', 'Uri Antulio Maldonado De Leon', 'VAMOS'),
('SUCHITEPÉQUEZ', 'CUYOTENANGO', 'Jorge Arturo Reyes Ceballos', 'VAMOS'),
('SUCHITEPÉQUEZ', 'MAZATENANGO', 'Carlos Estuardo Villagran', 'VAMOS'),
('SUCHITEPÉQUEZ', 'PATULUL', 'César Augusto Calderón Uribio', 'VAMOS'),
('SUCHITEPÉQUEZ', 'PUEBLO NUEVO', 'Diego Lux Lux', 'CABAL'),
('SUCHITEPÉQUEZ', 'RÍO BRAVO', 'Juan Francisco Lopez Diaz', 'VAMOS'),
('SUCHITEPÉQUEZ', 'SAMAYAC', 'Camilo Felipe Hernández Lopez', 'ELEFANTE'),
('SUCHITEPÉQUEZ', 'SAN ANTONIO SUCHITEPÉQUEZ', 'Edgar Mauricio Ovalle Siguan', 'VAMOS'),
('SUCHITEPÉQUEZ', 'SAN BERNARDINO', 'Herbert Juan Pablo Hurtado Paul', 'NOSOTROS'),
('SUCHITEPÉQUEZ', 'SAN FRANCISCO ZAPOTITLÁN', 'Carlos Rene Chavez Kestler', 'VAMOS'),
('SUCHITEPÉQUEZ', 'SAN GABRIEL', 'Remigio Noj Ramos', 'VAMOS'),
('SUCHITEPÉQUEZ', 'SAN JOSÉ EL ÍDOLO', 'Alfredo Oliva Lam', 'CABAL'),
('SUCHITEPÉQUEZ', 'SAN JOSÉ LA MÁQUINA', 'Candido Villagrán Pascual Ávalos', 'CABAL'),
('SUCHITEPÉQUEZ', 'SAN JUAN BAUTISTA', 'Victor Haroldo Oviedo Ajcalon', 'CABAL'),
('SUCHITEPÉQUEZ', 'SAN LORENZO', 'Henry Estuardo Ayala Dardon', 'VAMOS'),
('SUCHITEPÉQUEZ', 'SAN MIGUEL PANÁN', 'Gilberto Rocael Arauz Cal', 'CABAL'),
('SUCHITEPÉQUEZ', 'SAN PABLO JOCOPILAS', 'Melvin Paolo Macario Taquiej', 'VAMOS'),
('SUCHITEPÉQUEZ', 'SANTA BÁRBARA', 'Efrain Coche González', 'CABAL'),
('SUCHITEPÉQUEZ', 'SANTO DOMINGO SUCHITEPÉQUEZ', 'Marvin Gustavo Perez Gualip', 'VAMOS'),
('SUCHITEPÉQUEZ', 'SANTO TOMÁS LA UNIÓN', 'Pedro Augusto Chavaloc Aguilar', 'CABAL'),
('SUCHITEPÉQUEZ', 'ZUNILITO', 'Rudi Eduardo Edelman Cop', 'VAMOS'),
('TOTONICAPÁN', 'MOMOSTENANGO', 'Albino Cuyuch Chaj', 'CABAL'),
('TOTONICAPÁN', 'SAN ANDRÉS XECUL', 'Francisco Eduardo Chuc Paxtor', 'UNE'),
('TOTONICAPÁN', 'SAN BARTOLO', 'Pedro Arael Pérez Ruano', 'BIEN'),
('TOTONICAPÁN', 'SAN CRISTÓBAL TOTONICAPÁN', 'Carlos Enrique Say Mutz', 'CABAL'),
('TOTONICAPÁN', 'SAN FRANCISCO EL ALTO', 'José Pastor Hernández', 'UNE'),
('TOTONICAPÁN', 'SANTA LUCÍA LA REFORMA', 'Juan Chivalán Tiú', 'UNE'),
('TOTONICAPÁN', 'SANTA MARÍA CHIQUIMULA', 'Juan Carlos Carrillo Castro', 'CABAL'),
('TOTONICAPÁN', 'TOTONICAPÁN', 'Luis Alfredo Herrera Amado', 'CABAL'),
('ZACAPA', 'CABAÑAS', 'José Humberto Sandoval Castañeda', 'UNE'),
('ZACAPA', 'ESTANZUELA', 'Mirna Yohaira Vargas Trujillo', 'VAMOS'),
('ZACAPA', 'GUALÁN', 'Luis Alfredo Ortega Tobar', 'VAMOS'),
('ZACAPA', 'HUITÉ', 'Walter Joel Mateo Najera', 'CABAL'),
('ZACAPA', 'LA UNIÓN', 'Edvin Gustavo Galván', 'VAMOS'),
('ZACAPA', 'RÍO HONDO', 'Jorge Mario Pinto', 'VALOR'),
('ZACAPA', 'SAN DIEGO', 'Hugo Rene Villeda Portillo', 'VAMOS'),
('ZACAPA', 'SAN JORGE', 'Oscar David Trujillo Sánchez', 'VAMOS'),
('ZACAPA', 'TECULUTÁN', 'César Augusto Paiz Gómez', 'VAMOS'),
('ZACAPA', 'USUMATLÁN', 'Andi Natanael Pacheco Vásquez', 'VAMOS'),
('ZACAPA', 'ZACAPA', 'Karen Xiomara Ovalle Madrid', 'C.C. Por Amor a Zacapa');