/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ["Hanken Grotesk", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
                mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
                serif: ['Playfair Display', 'serif'],
            },
            colors: {
                'surface-dim': '#d8dadc',
                'inverse-primary': '#bcc7de',
                'inverse-on-surface': '#eff1f3',
                'on-primary': '#ffffff',
                'primary-base': '#091426',
                'outline-variant': '#c5c6cd',
                'secondary-fixed-dim': '#c0c1ff',
                'surface-bright': '#f7f9fb',
                'on-secondary-container': '#fffbff',
                'surface-container': '#eceef0',
                'primary-container-base': '#1e293b',
                'on-primary-fixed': '#111c2d',
                'secondary-container-base': '#6063ee',
                'surface-container-lowest': '#ffffff',
                'primary-fixed-dim': '#bcc7de',
                'primary-fixed': '#d8e3fb',
                'on-surface-variant': '#45474c',
                'surface-base': '#f7f9fb',
                'on-primary-container': '#8590a6',
                'on-secondary': '#ffffff',
                'surface-variant': '#e0e3e5',
                'tertiary': '#001815',
                'on-error-container': '#93000a',
                'on-tertiary': '#ffffff',
                'on-tertiary-container': '#28a094',
                'on-surface': '#191c1e',
                'on-primary-fixed-variant': '#3c475a',
                'on-secondary-fixed': '#07006c',
                'tertiary-fixed': '#89f5e7',
                'tertiary-fixed-dim': '#6bd8cb',
                'secondary-fixed': '#e1e0ff',
                'surface-container-highest': '#e0e3e5',
                'surface-container-low': '#f2f4f6',
                'on-tertiary-fixed': '#00201d',
                'inverse-surface': '#2d3133',
                'surface-tint': '#545f73',
                'surface-container-high': '#e6e8ea',
                'outline': '#75777d',
                'on-error': '#ffffff',
                'error': '#ba1a1a',
                'error-container': '#ffdad6',
                'tertiary-container': '#002f2a',
                'secondary-base': '#4648d4',
                'on-tertiary-fixed-variant': '#005049',
                'on-secondary-fixed-variant': '#2f2ebe',
                'background-base': '#f7f9fb',
                'on-background': '#191c1e',
                'primary': {
                    500: '#3b82f6',
                    600: '#2563eb',
                }
            },
            scale: {
                '103': '1.03',
            }
        },
    },
    plugins: [],
}
