/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ["Hanken Grotesk", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
                mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
                serif: ['Playfair Display', 'serif'],
                "body-lg": ["Manrope"],
                "headline-lg-mobile": ["Playfair Display"],
                "headline-lg": ["Playfair Display"],
                "label-md": ["Manrope"],
                "body-md": ["Manrope"],
                "label-sm": ["Manrope"],
                "headline-xl": ["Playfair Display"]
            },
            colors: {
                "on-secondary": "#273047",
                "on-primary-container": "#554300",
                "surface-container": "#1d2023",
                "surface-container-high": "#272a2d",
                "on-primary-fixed-variant": "#574500",
                "background": "#101417",
                "surface-bright": "#363a3d",
                "outline-variant": "#4d4635",
                "tertiary-fixed-dim": "#c1c6db",
                "surface-container-lowest": "#0b0f11",
                "error-container": "#93000a",
                "on-error": "#690005",
                "primary": "#f2ca50",
                "on-secondary-fixed-variant": "#3d465f",
                "on-primary-fixed": "#241a00",
                "secondary-container": "#3d465f",
                "on-secondary-container": "#acb4d2",
                "on-secondary-fixed": "#121b31",
                "on-tertiary-container": "#404556",
                "tertiary-fixed": "#dee1f7",
                "outline": "#99907c",
                "surface-tint": "#e9c349",
                "surface-dim": "#101417",
                "primary-container": "#d4af37",
                "inverse-on-surface": "#2d3134",
                "inverse-primary": "#735c00",
                "surface-container-highest": "#323538",
                "primary-fixed-dim": "#e9c349",
                "on-tertiary": "#2b3040",
                "surface-variant": "#323538",
                "primary-fixed": "#ffe088",
                "inverse-surface": "#e0e2e6",
                "on-background": "#e0e2e6",
                "tertiary": "#c9cde3",
                "on-surface": "#e0e2e6",
                "on-primary": "#3c2f00",
                "on-error-container": "#ffdad6",
                "secondary-fixed": "#dae2ff",
                "secondary": "#bdc6e4",
                "on-tertiary-fixed-variant": "#414657",
                "surface": "#101417",
                "surface-container-low": "#191c1f",
                "on-tertiary-fixed": "#161b2a",
                "tertiary-container": "#aeb2c7",
                "on-surface-variant": "#d0c5af",
                "secondary-fixed-dim": "#bdc6e4",
                "error": "#ffb4ab",
                "primary-base": "#091426",
                "secondary-base": "#4648d4",
                "background-base": "#0a0f1e",
                "surface-base": "#101417",
                "primary-gold": "#f2ca50",
                "primary-gold-dark": "#d4af37",
                "brand-midnight": "#0a0f1e",
                "border-card": "rgba(153, 144, 124, 0.2)"
            },
            scale: {
                '103': '1.03',
            }
        },
    },
    plugins: [],
}
