/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-secondary-container": "#5c647a",
                "surface-container-highest": "#e1e3e4",
                "on-error-container": "#93000a",
                "on-surface": "#191c1d",
                "on-secondary-fixed-variant": "#3f465c",
                "on-secondary": "#ffffff",
                "surface-variant": "#e1e3e4",
                "tertiary-fixed": "#acf847",
                "inverse-primary": "#abd600",
                "on-primary-fixed-variant": "#3c4d00",
                "surface": "#f8f9fa",
                "tertiary-fixed-dim": "#91db2a",
                "on-tertiary": "#ffffff",
                "surface-container-low": "#f3f4f5",
                "inverse-surface": "#2e3132",
                "primary-fixed": "#c3f400",
                "on-error": "#ffffff",
                "secondary": "#565e74",
                "outline-variant": "#c4c9ac",
                "surface-container-high": "#e7e8e9",
                "background": "#f8f9fa",
                "on-tertiary-container": "#4a7700",
                "tertiary": "#416900",
                "surface-dim": "#d9dadb",
                "error-container": "#ffdad6",
                "on-tertiary-fixed-variant": "#304f00",
                "on-background": "#191c1d",
                "inverse-on-surface": "#f0f1f2",
                "tertiary-container": "#c2ff75",
                "on-primary-container": "#5b7300",
                "secondary-fixed-dim": "#bec6e0",
                "surface-tint": "#506600",
                "on-secondary-fixed": "#131b2e",
                "on-primary-fixed": "#161e00",
                "error": "#ba1a1a",
                "secondary-container": "#dae2fd",
                "surface-container-lowest": "#ffffff",
                "primary-fixed-dim": "#abd600",
                "surface-container": "#edeeef",
                "outline": "#747a60",
                "on-primary": "#ffffff",
                "secondary-fixed": "#dae2fd",
                "surface-bright": "#f8f9fa",
                "on-tertiary-fixed": "#102000",
                "primary": "#506600",
                "primary-container": "#ccff00",
                "on-surface-variant": "#444933"
            },
            borderRadius: {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            spacing: {
                "space-2xs": "0.25rem",
                "space-sm": "0.75rem",
                "space-2xl": "3rem",
                "space-lg": "1.5rem",
                "gutter-mobile": "1rem",
                "gutter-desktop": "1.5rem",
                "space-3xl": "4.5rem",
                "space-xl": "2rem",
                "space-xs": "0.5rem",
                "space-md": "1rem",
                "container-max": "1280px"
            },
            fontFamily: {
                "label-meta": ["Plus Jakarta Sans", "sans-serif"],
                "headline-xl": ["Oswald", "sans-serif"],
                "display-hero": ["Oswald", "sans-serif"],
                "body-md": ["Plus Jakarta Sans", "sans-serif"],
                "body-sm": ["Plus Jakarta Sans", "sans-serif"],
                "headline-md": ["Oswald", "sans-serif"],
                "body-lg": ["Plus Jakarta Sans", "sans-serif"],
                "stat-display": ["Oswald", "sans-serif"],
                "display-hero-mobile": ["Oswald", "sans-serif"],
                "label-pill": ["Plus Jakarta Sans", "sans-serif"],
                "headline-lg": ["Oswald", "sans-serif"]
            },
            fontSize: {
                "label-meta": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
                "headline-xl": ["36px", { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "700" }],
                "display-hero": ["56px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
                "body-sm": ["13px", { lineHeight: "18px", fontWeight: "500" }],
                "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "stat-display": ["48px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "display-hero-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
                "label-pill": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "700" }],
                "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "0em", fontWeight: "600" }]
            }
        },
    },
    plugins: [],
}

